### ISSUE TITLE
TCP socket_connect has no timeout method

### ISSUE THREAD

**Issue by wuwx** [eerimoq/simba#56]
in my `main.c` code, and try to connect to a invalid ip and port

```
#include "simba.h"

static struct socket_t socket;
static struct inet_addr_t remote_host_address;
static struct inet_addr_t local_host_address;

int main()
{
    sys_start();

    socket_open_tcp(&socket);
    inet_aton("8.8.8.8", &remote_host_address.ip);
    remote_host_address.port = 80;
    inet_aton("0.0.0.0", &local_host_address.ip);
    local_host_address.port = 6000;
    socket_bind(&socket, &local_host_address);
    socket_connect(&socket, &remote_host_address);

    std_printf("can you see it ?\r\n");
}

```

the code never run to

`std_printf("can you see it ?\r\n");`

```
--- Miniterm on /dev/cu.SLAB_USBtoUART  38400,8,N,1 ---
--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---

File system mounted.
Connecting to WiFi with SSID 'MyWiFiSSID'.
Waiting for a connection to WiFi with SSID 'MyWiFiSSID'.
Waiting for a connection to WiFi with SSID 'MyWiFiSSID'.
Waiting for a connection to WiFi with SSID 'MyWiFiSSID'.
Connected to WiFi with SSID 'MyWiFiSSID'. Got IP address '192.168.38.149'.

$ 
$ 
$ 
$ 
$ 
$ 
$ 
$ 
$ 
```

**Comment by eerimoq** [comment]
I've been busy porting Simba to the ESP32, and it actually works now! I'll have a look at this and the MQTT issue soonish =)

**Comment by wuwx** [comment]
wow~~ greate!
in these days i also findout some esp32 dev board in china taobao.com ......

**Comment by eerimoq** [comment]
The behaviour of ``socket_connect()`` is now:

- Connecting to invalid IP address will fail after a timeout in the LwIP stack.
- Connecting to a valid IP but an invalid port will result in a failed connection attempt, given that the remote host sends the RST packet as response to the SYN packet. Otherwise a timeout will occur in the LwIP stack.

Behaviour for a WiFi that is disconnected has not been tested. It will likely result in a failed connect attempt.
