### ISSUE TITLE
request implement ssl/tls layer

### ISSUE THREAD

**Issue by wuwx** [eerimoq/simba#62]
improve data security

**Comment by eerimoq** [comment]
I created a file ``inet/ssl.h``, with a few functions to initialize, read and write data over SSL/TLS. See commit c707e42fd046344af81a55620484c78ab9373e5d.

I don't have any experiance using SSL/TLS libraries. Seems like mbedTLS is popular. What alternatives are free and open source? Feel free to make changes to ssl.h and add more files for SSL.

I guess the ssl instance should be a channel, since it is a data transport protocol (with some security on top).

**Comment by eerimoq** [comment]
Added bais client and server examples in a [test suite](https://github.com/eerimoq/simba/blob/master/tst/inet/ssl/main.c) to understand how to use the SSL module interface.

**Comment by eerimoq** [comment]
The plan is to design the interface as the Python [ssl module](https://docs.python.org/3/library/ssl.html) interface.

**Comment by wuwx** [comment]
https://github.com/espressif/esp8266-rtos-sample-code/tree/master/04Protocal/SSL_Demo

esp8266 rtos ssl demo project

**Comment by eerimoq** [comment]
I've successfully setup a SSL server side socket between a ESP32 and my PC! Needs tuning of memory usage and, most importantly, a valid entropy source implementation to ensure(?) secure communication.

See the [example](https://github.com/eerimoq/simba/blob/master/examples/ssl_server/main.c) for usage.

**Comment by eerimoq** [comment]
The first version is pushed and released. Let me know if there are issues or features that are missing. Only server side is implemented.

**Comment by eerimoq** [comment]
Both client and server side has been implemented and seems to work. Ther eare still functionality missing that should be added to make the security better, like verify the hostnames.
